NEO SYSTEM TECHNOLOGY/Controllers/ReceiptController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NEO_SYSTEM_TECHNOLOGY.Data;
using NEO_SYSTEM_TECHNOLOGY.Entity;
using NEO_SYSTEM_TECHNOLOGY.ViewModels;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace NEO_SYSTEM_TECHNOLOGY.Controllers
{
    public class ReceiptController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public ReceiptController(IHostingEnvironment hostingEnvironment)
        {
            _context = new ApplicationDbContext();
            _hostingEnvironment = hostingEnvironment;            
        }

        public IActionResult Index()
        {
            var receipList = _context.Receipts.Include(p => p.Dogovor).ThenInclude(p => p.Organization).ToList();
          

            return View(receipList);
        }

        public IActionResult AddNewReceipt(int dogovorId)
        {
            var dogovorInDb = _context.Dogovors.Include(p => p.Receipt).Include(p => p.Organization).SingleOrDefault(p => p.ID == dogovorId);
            var viewModel = new DogovorReceiptVM
            {
                Order = dogovorInDb.OrderHeader,
                OrgName = dogovorInDb.Organization.Name,
                DogovorId = dogovorInDb.ID
            };
            return View("ReceiptForm", viewModel);
        }

        public IActionResult Save(DogovorReceiptVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                var vm = new DogovorReceiptVM
                {
                    Order = viewModel.Order,
                    OrgName = viewModel.OrgName
                };
                return View("ReceiptForm", vm);
            }

            string fileName = null;
            string uploadFolder = Path.Combine(_hostingEnvironment.WebRootPath, "pdfFile");
            fileName = Guid.NewGuid().ToString() + "_" + viewModel.FormFile.FileName;
            string filePath = Path.Combine(uploadFolder, fileName);
            viewModel.FormFile.CopyTo(new FileStream(filePath, FileMode.Create));



            Receipt receipt = new Receipt
            {
                AccountNumber = viewModel.AccountNumber ?? default,
                AmountFaceValue = viewModel.AmountFaceValue ?? default,
                IsVatIncluded = viewModel.IsVatIncluded,
                Currency = viewModel.Currency,
                PaymentSum = viewModel.PaymentSum ?? default,
                DateFaceValue = viewModel.DateFaceValue ?? default,
                PaymentDate = viewModel.PaymentDate ?? default,
                DogovorId = viewModel.DogovorId,
                Content = fileName
            };

            _context.Add(receipt);
            _context.SaveChanges();




            return RedirectToAction("Index");
        }
    }
}

NEO SYSTEM TECHNOLOGY/Views/Receipt/Index.cshtml
@model IEnumerable<NEO_SYSTEM_TECHNOLOGY.Entity.Receipt>

  


    <div style="margin: 50px">
        @foreach (var item in Model)
    {

        var filePath = "/PdfFile/" + item.Content;

        <p>@item.AccountNumber</p>
        <p>@item.Dogovor.OrderHeader</p>
        <p>@item.Dogovor.Organization.Name</p>
        <embed src="@filePath" type="application/pdf" height="400px" width="40%" class="responsive">
        <p> <a href="@filePath">Скачать</a></p>
@* 
        <embed type="application/pdf"
               src="@filePath"
               width="100%" height="500" alt="pdf" pluginspage="http://www.adobe.com/products/acrobat/readstep2.html"
               background-color="0xFF525659" top-toolbar-height="56" full-frame="" internalinstanceid="21"
               title="CHROME"> *@

     @*    <iframe src="@filePath"
                style="width:600px; height:500px;" frameborder="0"></iframe> *@

      @*   <h1>PDF Example by Object Tag</h1>
        <object data="@filePath" type="application/pdf" width="100%" height="500px">
            <p>Unable to display PDF file. <a href="@filePath">Download</a> instead.</p>
        </object> *@
    }
    </div>

NEO SYSTEM TECHNOLOGY/Views/Receipt/ReceiptForm.cshtml
@model NEO_SYSTEM_TECHNOLOGY.ViewModels.DogovorReceiptVM
@using NEO_SYSTEM_TECHNOLOGY.Entity.Enum



@using (Html.BeginForm("Save", "Receipt", FormMethod.Post, new { style = "margin: 20px;", enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary()
    ;

    <div style="margin: 0px 5px;">
        <h2>@Model.OrgName</h2>
    </div>
    <div style="margin: 0px 5px;">
        <h2>@Model.Order</h2>
    </div>

    <div class="form-group" style="margin: 15px 15px">
        @Html.LabelFor(p => p.AccountNumber, new { style = "margin: 0px 5px;" })
        @Html.TextBoxFor(p => p.AccountNumber, new { @class = "form-control text-box js-box", style = "width:500px; height:35px" })
    </div>

    <div class="form-group" style="margin:15px 15px">
        @Html.LabelFor(p => p.AmountFaceValue, new { style = "margin: 0px 5px;" })
        @Html.TextBoxFor(p => p.AmountFaceValue, new { @class = "form-control text-box js-box", style = "width:500px; height:35px" })
    </div>

    <div class="checkbox" style="margin: 15px 0px">
        <label>
            @Html.CheckBoxFor(p => p.IsVatIncluded, new { style = "width:50px; height:20px" }) НДС 15%
        </label>
    </div>

    <div class="form-group" style="margin: 15px 15px">
        @Html.LabelFor(p => p.PaymentSum, new { style = "margin: 0px 5px;" })
        @Html.TextBoxFor(p => p.PaymentSum, new { @class = "form-control text-box", style = "width:500px; height:35px" })
    </div>

    <div class="form-group" style="margin:15px 15px">
        @Html.LabelFor(p => p.DateFaceValue, new { style = "margin: 0px 5px;" })
        @Html.TextBoxFor(p => p.DateFaceValue, new { @class = "form-control text-box", style = "width:500px; height:35px" })
    </div>

    <div class="form-group" style="margin:15px 15px">
        @Html.LabelFor(p => p.PaymentDate, new { style = "margin: 0px 5px;" })
        @Html.TextBoxFor(p => p.PaymentDate, new { @class = "form-control text-box", style = "width:500px; height:35px" })
    </div>

    <div class="form-group" style="margin:15px 15px">
        @Html.LabelFor(p => p.Currency, new { style = "margin: 0px 5px;" })
        @Html.DropDownListFor(p => p.Currency, Html.GetEnumSelectList<Currency>(), "Выберите валюту", new { @class = "form-control text-box", style = "width:500px; height:35px" })
    </div>

    <div class="form-group" style="margin:15px 15px">      
            <dl>
                <dt>
                    <label asp-for="@Model.FormFile" class="control-label"></label>
                </dt>
                <dd>
                <input asp-for="@Model.FormFile" type="file" class="file-input">
                </dd>
            </dl>
    </div>

    @Html.HiddenFor(p => p.OrgName)
    @Html.HiddenFor(p => p.DogovorId)

    <button type="submit" class="btn btn-default btn-outline-primary" style="margin: 10px 20px; width:200px;">Сохранить</button>
}